{{- if eq .Values.secretsProvider.type "azure" }}
{{- if .Values.secrets }}
# secret provider for the deployment object
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "k8s-service.fullname" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    {{- toYaml .Values.secretsProvider.parameters | nindent 4 }}
    objects:  |
      array:
        {{ range .Values.secrets }}
        - |
          objectName: {{ .name }}
          objectType: secret   
        {{ end }}         
  secretObjects:
  - data:
    {{ range .Values.secrets }}
    - key: {{ .name }}
      objectName: {{ .name }}
    {{ end }}           
    secretName: {{ include "k8s-service.fullname" . }}
    type: Opaque    

# secret provider for the pre-intall hook
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "k8s-service.fullname" . }}-pre-install
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    {{- toYaml .Values.secretsProvider.parameters | nindent 4 }}
    objects:  |
      array:
        {{ range .Values.secrets }}
        - |
          objectName: {{ .name }}
          objectType: secret   
        {{ end }}         
  secretObjects:
  - data:
    {{ range .Values.secrets }}
    - key: {{ .name }}
      objectName: {{ .name }}
    {{ end }}           
    secretName: {{ include "k8s-service.fullname" . }}-pre-install
    type: Opaque    
{{- end }}                          
{{- end }}