apiVersion: v1
kind: Secret
metadata:
  namespace: app-namespace
  name: secret-name
  labels:
    app: app-scaler-name-label
data:
  management-connectionstring: base64_encoded_connection_string
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  namespace: app-namespace
  name: trigger-auth-name
spec:
  secretTargetRef:
  - parameter: connection
    name: secret-name
    key: management-connectionstring
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: app-namespace
  name: app-scaler-name-label
spec:
  scaleTargetRef:
    name: deployment-to-scale-name
  pollingInterval: 1 # Optional. Default: 30 seconds - checks for the changes
  cooldownPeriod: 20 # Optional. Default: 300 seconds - shutdown - need to find a sweet spot , Its better to keep default so that we don't interrupt any running processes
  minReplicaCount: 2 # Minimum replica count.
  maxReplicaCount: 4 # Optional. Default: 100
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: sbus-topic-name
      subscriptionName: sbus-topic-subscription-name
      namespace: sbus-namespace # NOT Kuberenetes namespace!
      messageCount: "1" # need to find a sweet spot. How many messages should trigger scaling
    authenticationRef:
      name: trigger-auth-name
